usr/lib/lib*.so
usr/lib/lib*.a
usr/lib/pkgconfig
include/*.h usr/local/include/openvswitch
include/openflow/*.h usr/local/include/openvswitch/openflow
include/openvswitch/*.h usr/local/include/openvswitch/openvswitch
include/sparse/*.h usr/local/include/openvswitch/sparse
include/sparse/arpa/*.h usr/local/include/openvswitch/sparse/arpa
include/sparse/netinet/*.h usr/local/include/openvswitch/sparse/netinet
include/sparse/sys/*.h usr/local/include/openvswitch/sparse/sys
lib/*.h usr/local/include/openvswitch/lib
